### ISSUE TITLE
Needs check for distro

### ISSUE THREAD

**Issue by JeffMatson** [QROkes/webinoly#2] opened 2017-10-03 04:54 UTC
Looks like an Ubuntu-based server is assumed, but no checks are present to detect if it is or not.

**Comment by JeffMatson** [comment] 2017-10-03 04:59
https://github.com/QROkes/webinoly/blob/master/lib/install#L137

This is also another instance of it. The rest of the script would likely run on Debian or derivatives, but a ppa won't.

**Comment by QROkes** [comment] 2017-10-03 18:44
Duplicate of #1 
Maybe in the future we will support Debian. Actually, I have no experience with Debian, but I think it's a good idea and shouldn't be difficult considering Ubuntu is a Debian derivative.

**Comment by JeffMatson** [comment] 2017-10-03 19:13
Should be super simple. Really, all you’re doing is a bit of detection. If I get the time, I’ll toss in a PR for you.

Jeff

**Comment by QROkes** [comment] 2017-12-05 04:10
Fixed in v1.1.0

**Closed by QROkes** 2017-12-05 04:10 UTC
