### ISSUE TITLE
assign separate user permissions to each website for multiuser context

### ISSUE THREAD

**Issue by zenny** [QROkes/webinoly#13] opened 2018-09-20 07:20 UTC
Hi,

The script looks very nifty. However, it appears that it is limited to assign www-data user and group as sftp or web domain owner.

Instead, may I suggest to create a separate user/group and other users for each domain? 

What I meant is to create a clientID for each user and userID for each website created similar to ISPConfig3? 

client1 shall own web1, web3 ..
client2 shall own web2, web7
client3 can own web 4, web5 and web8 and so on.

The clients and webs shall only have sftp access, no system access. SSH access may be made to switched on or off.

This would be helpful in multiuser environment.

Cheers,
/z

**Comment by QROkes** [comment] 2018-09-20 19:12
Send me a Pull Request.

**Comment by zenny** [comment] 2018-11-20 08:09
> Send me a Pull Request.

Cannot create a new pull request, no matter what I do.

The approach I suggested could be achieved by using 'adduser/useradd' command by creating with shell access disabled and then 'chown' to the specific group and user.

Cheers,
/z

**Comment by QROkes** [comment] 2018-11-20 20:19
**I think it's not that simple.**
Right now Nginx is configured to work with www-data user, also there is a well known issue in multi-user enviroments when you try to purge fastcgi cache.
Maybe you will have to modify some PHP configurations too.
Regards.

**Comment by QROkes** [comment] 2019-01-07 00:57
Duplicate of #10

**Closed by QROkes** 2019-01-07 00:57 UTC
Labels: duplicate
