### ISSUE TITLE
Bash shell check may cause blocking behavior

### ISSUE THREAD

**Issue by Julien-prrs** [QROkes/webinoly#53] opened 2022-02-12 00:27 UTC
Hello,

I've just updated my webinoly installation to the latest version few hours ago,  then right after the update I noticed that I was not able to run `webinoly` again without getting the following error:

```bash
BASH Shell is required!
```

After looking at the code, I've found that this error came from the following condition, which check if my login shell is `bash` (which is not).

```bash
# Check for BASH Shell
if [[ -z $(grep -E "^${SUDO_USER:-${USER}}\:.*\/bash.*$" /etc/passwd) ]]; then
	echo "$(tput setaf 1)BASH Shell is required!$(tput sgr0)"
	exit 1
fi
```

I can't see any reasons why my login shell must be `bash`, which leads me to think that this isn't the real expectations of this condition.

Can you confirm what is she supposed to do ? That way I would be able to submit a fix.

**Comment by baiyuanlab** [comment] 2022-02-12 12:42
> **Hi Julien,**
> 
> We noticed that a few things were not working well when a different shell is used (like ZSH), then we tried checking some env variables like `$BASH` or `$SHELL`, etc. but none of these is reliable enough. That's why we end up implementing that solution checking directly into `passwd` file.
> 
> Any suggestions?

Hello,

We also found this problem yesterday, this problem occurs in GCP, it is normal in Vultr.

See attached.
![image](https://user-images.githubusercontent.com/5700175/153711734-ef4a6257-0310-4d5b-8c59-2ab61ec4b394.png)

**Comment by QROkes** [comment] 2022-02-12 16:13
**Hi @baiyuanlab** 

The problem is that `$SHELL` variable is not reliable, you can change to a different shell and it will still have the same value.

- **For people not using BASH this is the expected behavior.** _You should be blocked from the initial installation._
- For people updating their servers, this should be a notice to change their shell to BASH, or for more experienced people this can be easily bypassed in case of "urgency".

Of course, I'm aware that we can improve this "check" function:
- Like in your case, seems like you are using BASH but for some reason your `/etc/passwd` has a different value. **We need to know why you or your cloud provider is changing this Ubuntu default value.** Then we will be able to improve the way we are doing this "check".

**Comment by Julien-prrs** [comment] 2022-02-12 21:05
> **Hi Julien,**
> 
> We noticed that a few things were not working well when a different shell is used (like ZSH), then we tried checking some env variables like `$BASH` or `$SHELL`, etc. but none of these is reliable enough. That's why we end up implementing that solution checking directly into `passwd` file.
> 
> Any suggestions?

After various unsuccessful and/or unreliable tests, I may have found an alternative. 

```bash
if [[ $(tr -d '\0' < /proc/$$/cmdline) != /bin/bash* ]]; then
        echo "$(tput setaf 1)BASH Shell is required!$(tput sgr0)"
        exit 1
fi
```

I don't know if this solution is reliable enough, but (in my case) it works !

**Comment by Julien-prrs** [comment] 2022-02-12 21:31
I've just think about that, but, does the shebang not already force the script execution with bash ? No matter what shell is running the command.

For exemple, running `webinoly` within a `fish` shell (which have a different scripting syntax, not like zsh) and with `bash` as login shell (to bypass the check) is working properly.

**Comment by QROkes** [comment] 2022-02-13 03:23
@Julien-prrs and @baiyuanlab 

Please, can you check this info:
- What cloud provider are you using.
- The value for "root" in `/etc/passwd`
- If you are using a different user than "root", check the value for this user too.

By default, they should be set to Bash, would be very useful if we check why your cloud provider is changing these values. Or maybe to know under what conditions these values are changed.

**Comment by QROkes** [comment] 2022-02-13 19:43
@Julien-prrs I think I wasn't clear enough, so here is again my previous comment.

> **For people not using BASH this is the expected behavior.** _You should be blocked from the initial installation._

In other words: This is exactly the situation this check is trying to prevent.
I will wait for @baiyuanlab answer and after that I will close this issue.

**Comment by Julien-prrs** [comment] 2022-02-13 23:56
> @Julien-prrs I think I wasn't clear enough, so here is again my previous comment.
> 
> > **For people not using BASH this is the expected behavior.** _You should be blocked from the initial installation._
> 
> In other words: This is exactly the situation this check is trying to prevent. I will wait for @baiyuanlab answer and after that I will close this issue.

@QROkes Your previous comment was very clear, but I think you didn't really understand my problem. Maybe I wasn't specific enough in my first comment so, I'll try to explain it with more details.

Yes, I'm using zsh on my servers (and also fish sometimes). But now because of this check, i'm switching to bash (using a simple `bash` command) to run webinoly. But (and thats why i've created this issue) it's not working, because the check is based on the login shell where it should be based on the interactive shell.

Also, I'm not a scriping expert but, as I said in one of my previous comment, does the shebang not stand to force script execution using a specified interpretor (`/bin/bash` for here) ? If I'm right, do this check is really required ?  Do you have some example of things that were not working properly when running webinoly from another shell ?

As I said, I'm no expert, so I could be wrong.

**Comment by QROkes** [comment] 2022-02-14 01:16
Try this in ZSH: `sudo site example.com -proxy=[localhost:8082]`

The problem is in the Command Line Syntax, not in the script, per se. Webinoly has a lot of commands with this kind of arguments `-arg=[...<values>...]` and as you can see they all will fail.

I know that experienced users can handle it very easily, the problem really is that a lot of people will not know what it's really happening and just assume that Webinoly is failing, even when they are using the examples as they are shown in the official documentation.

**Comment by QROkes** [comment] 2022-02-14 21:39
> But (and thats why i've created this issue) it's not working, because the check is based on the login shell where it should be based on the interactive shell.

You're right on this point!
I'm testing your `cmdline` solution, and also this:

`[[ -z $(sh -c 'ps -p $$ -o ppid=' | xargs -i readlink -f /proc/{}/exe | grep -E "^\/.*\/bash$") ]] && echo "fail" || echo "success"`

Any suggestion is appreciated!

**Comment by Julien-prrs** [comment] 2022-02-14 23:34
@QROkes Sorry I'm very busy at this time, I'll try to take a look at this as soon as I can to make some suggestions.

**Comment by baiyuanlab** [comment] 2022-02-15 05:17
> Cloud provider: OVH
> root: `/bin/bash`
> my user: `/bin/zsh` (changed by myself, default was `/bin/bash`)

Cloud provider: Google Cloud 
root: /bin/bash
my user: /bin/zsh (changed by myself, default was /bin/bash)

> @Julien-prrs and @baiyuanlab
> 
> Please, can you check this info:
> 
> * What cloud provider are you using.
> * The value for "root" in `/etc/passwd`
> * If you are using a different user than "root", check the value for this user too.
> 
> By default, they should be set to Bash, would be very useful if we check why your cloud provider is changing these values. Or maybe to know under what conditions these values are changed.

Cloud provider: Google Cloud 
The value for "root" in `/etc/passwd`: /bin/bash
![image](https://user-images.githubusercontent.com/5700175/153997069-e3653921-7e95-4801-b48d-8e961a50fc57.png)

**Comment by QROkes** [comment] 2022-02-15 14:58
@baiyuanlab Just to confirm: 
Your case is the same as @Julien-prrs you are using ZSH too?

If this is the case, I'm thinking the most viable solution will be:

- As @Julien-prrs suggested, we will check for "interactive shell", instead of "login shell".
- Using Webinoly directly in a shell different than Bash will be still blocked.
- People using a different shell will be able to run Webinoly changing the interactive shell, but changing the default login shell will not be required.

Any thoughts?

**Comment by baiyuanlab** [comment] 2022-02-17 01:23
> 

@QROkes 

These three practices, we think are great! 
Later, we did a test, create a new sudo user, Webinoly can work correctly and the prompt "BASH Shell is required!" will no longer appear.

**Comment by QROkes** [comment] 2022-02-17 23:34
I have not found a reliable way to check for the "interactive shell" used by the user to run the script.

For example:
`# Default shell is bash
zsh
sudo webinoly -v`

We can see the default shell, also we can see the script is running in a Bash subshell.
**But how can I see that ZSH was used to execute the script?**

**Any help is appreciated!**

For now, the Bash check will be removed and I will put some similar checks in the "verify" function to give a message recommending Bash to prevent errors with unsupported syntax since Webinoly is tested and documented based on Bash.

**Comment by Julien-prrs** [comment] 2022-02-22 23:52
Finally got some free times to dive into this issue.

> I have not found a reliable way to check for the "interactive shell" used by the user to run the script.

Unfortunately, with the little time I've got these days to dive into this , I didn't found any reliable enough solutions too 🤔.

But, I think that having an explicit warning message instead of the current error can be a temporary "solution" to not force users to change their login shell each time they run a webinoly command.

In the following next weeks I'll try to take more time to study that problem and try to find a solution 🤞.

Maybe we can find a solution from the source code of another tool that already faced this kind of problem in the past ? Any idea ?

**Closed** 2022-03-05 16:25 UTC
Labels: enhancement, good first issue, accepted and scheduled

**Comment by Julien-prrs** [comment] 2022-03-05 19:22
> Webinoly v1.16.2 has been released! A better check for "interactive" shell, instead of login shell has been included.
> 
> I need your feedback!

I've just updated one of my server to Webinoly 1.16.2, and it sounds great to me !

**Comment by annahri** [comment] 2022-08-24 02:39
This is not working when I switch user from another user. For example: `root# su - anotheruser`

Any further webinoly commands won't work for that user:
```
$ site
BASH Shell is required! (su-anotheruser)
$ webinoly
BASH Shell is required! (su-anotheruser)
```
